package wallet

/// Structs ///

type WalletConfig struct {
	Nickname   string
	PrivateKey string
	Addresses  []WalletAddress // cached generated addresses, will be lost of local db is wiped
}

/*
	WalletAddress is an address generated by the wallet's privateKey + secret + salt.
*/
type WalletAddress struct {
	Nickname      string
	PrivateKey    string
	PublicAddress string
	NativeBalance string
	Tokens        []ERC20Token
}

/*
	ERC20 Token config, this will be tracked for each wallet address.
*/
type ERC20Token struct {
	Name     string
	Symbol   string
	Decimals uint8
	Balance  string
}
