package wallet

import (
	"crypto/ecdsa"
)

type WalletConfig struct {
	Nickname   string
	PrivateKey *ecdsa.PrivateKey
	Chain      ChainConfig
	Addresses  []WalletAddress // cached generated addresses, will be lost of local db is wiped
}

/*
	WalletAddress is an address generated by the wallet's privateKey + secret + salt.
*/
type WalletAddress struct {
	Nickname      string
	PrivateKey    *ecdsa.PrivateKey
	PublicAddress string
	NativeBalance string
	Tokens        []ERC20Token
}

/*
	Chain config on which the wallet is created.
*/
type ChainConfig struct {
	Id   int
	Name string
	RPC  string
}

/*
	ERC20 Token config, this will be tracked for each wallet address.
*/
type ERC20Token struct {
	Name     string
	Symbol   string
	Address  string
	Decimals uint8
	Balance  string
}
